format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

add_newline = false

palette = "rose-pine"

[palettes.rose-pine]
subtle = '#908caa'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[line_break]
disabled = false

[directory]
truncation_length = 4
style = "fg:foam"

[character]
success_symbol = "[❯](pine)"
error_symbol = "[❯](love)"
vimcmd_symbol = "[❮](pine)"

[git_branch]
format = "[$branch]($style)"
style = "fg:subtle"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "fg:rose"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "fg:subtle"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:gold"

[python]
format = "[$virtualenv]($style) "
style = "fg:subtle"

